const TRAVEL_CURRENCIES = ['USD', 'EUR', 'GBP', 'JPY', 'INR'];
const FALLBACK_CURRENCIES = ['AUD', 'CAD', 'CHF'];
const CURRENCY_SYMBOLS = { USD: '$', EUR: '€', GBP: '£', JPY: '¥', INR: '₹', AUD: 'A$', CAD: 'C$', CHF: 'Fr' };
const CACHE_TTL_HOURS = 24;
const HISTORY_CACHE_TTL_DAYS = 7;
const MAX_HISTORY_ENTRIES = 100;
const MAX_FAVORITES = 10;
const CONVERSION_DECIMAL_PLACES = 2;
const RATE_DECIMAL_PLACES = 4;
const EXCHANGERATE_API_BASE = 'https://v6.exchangerate-api.com/v6';

module.exports = {
    TRAVEL_CURRENCIES,
    FALLBACK_CURRENCIES,
    CURRENCY_SYMBOLS,
    CACHE_TTL_HOURS,
    HISTORY_CACHE_TTL_DAYS,
    MAX_HISTORY_ENTRIES,
    MAX_FAVORITES,
    CONVERSION_DECIMAL_PLACES,
    RATE_DECIMAL_PLACES,
    EXCHANGERATE_API_BASE
};
